site_name: HYH的末影箱

theme:
  name: 'material'
  logo: 'logo.png'
  favicon: 'logo.png'
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: indigo
      accent: indigo
  features:
    - navigation.tabs
    - navigation.top
    - header.autohide
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate

repo_url: https://github.com/Hanzawa-Jeb/HYH-Ender-chest
repo_name: Hanzawa-Jeb/Ender-chest

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Hanzawa-Jeb/

nav:
  - 主页: index.md
  - 工程:
      - 工程图学笔记:
          螺纹与螺纹紧固件: Engineering/notes/螺纹与螺纹紧固件.md
          表面结构要求: Engineering/notes/表面结构要求.md
          齿轮: Engineering/notes/齿轮.md
          各类视图: Engineering/notes/各类视图.md
          滚动轴承: Engineering/notes/滚动轴承.md
          各类零件的视图选择: Engineering/notes/各类零件的视图选择.md
          键与销: Engineering/notes/键与销.md
          零件工艺结构简介: Engineering/notes/零件工艺结构简介.md
          极限与配合与几何公差: Engineering/notes/极限与配合与几何公差.md
          零件常见结构的尺寸注法: Engineering/notes/零件常见结构的尺寸注法.md
          尺寸标注: Engineering/notes/尺寸标注.md
          CAD: Engineering/notes/CAD.md
          多种投影方式: Engineering/notes/多种投影方式.md
          零件图与装配图: Engineering/notes/零件图与装配图.md
      - 工程图学历年题: Engineering/tests/MG_Dload_index.md
