site_name: HYH的末影箱

theme:
  name: 'material'
  logo: 'logo.png'
  favicon: 'logo.png'
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: indigo
      accent: indigo
  features:
    - navigation.tabs
    - navigation.top
    - header.autohide
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate

repo_url: https://github.com/Hanzawa-Jeb/HYH-Ender-chest
repo_name: Hanzawa-Jeb/Ender-chest

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Hanzawa-Jeb/

nav:
  - 主页: index.md
  - 工程:
      - 工程图学笔记:
          螺纹与螺纹紧固件: Engineering/notes/螺纹与螺纹紧固件.md
          表面结构要求: Engineering/notes/表面结构要求.md
          齿轮: Engineering/notes/齿轮.md
          各类视图: Engineering/notes/各类视图.md
          滚动轴承: Engineering/notes/滚动轴承.md
          各类零件的视图选择: Engineering/notes/各类零件的视图选择.md
          键与销: Engineering/notes/键与销.md
          零件工艺结构简介: Engineering/notes/零件工艺结构简介.md
          极限与配合与几何公差: Engineering/notes/极限与配合与几何公差.md
          零件常见结构的尺寸注法: Engineering/notes/零件常见结构的尺寸注法.md
          尺寸标注: Engineering/notes/尺寸标注.md
          CAD: Engineering/notes/CAD.md
          多种投影方式: Engineering/notes/多种投影方式.md
          零件图与装配图: Engineering/notes/零件图与装配图.md
      - 工程图学历年题: Engineering/tests/MG_Dload_index.md
  - 计算机科学:
      - 计算机语言基础:
          - C:
              - C程序设计基础及实验(C尖)应试笔记:
                  - 变量凸图的内容的大小: CS/C/应试/变量凸图的内容的大小.md
                  - 标准输入输出: CS/C/应试/标准输入输出.md
                  - 传统限制: CS/C/应试/传统限制.md
                  - 迭代关系For语句: CS/C/应试/迭代关系For语句.md
                  - 多分实现rich语句: CS/C/应试/多分实现rich语句.md
                  - 格式说明符中相同的使用: CS/C/应试/格式说明符中相同的使用.md
                  - 关键字与标识符: CS/C/应试/关键字与标识符.md
                  - 函数指针: CS/C/应试/函数指针.md
                  - 结构体内存Struct: CS/C/应试/结构体内存Struct.md
                  - 类型定义: CS/C/应试/类型定义typedefined.md
                  - 应对关系: CS/C/应试/应对关系if-elsepair.md
                  - 版卷break: CS/C/应试/版卷break.md
                  - 取空间大小: CS/C/应试/取空间大小.md
                  - 三目运算符: CS/C/应试/三目运算符.md
                  - 数值各与指针之间的区别: CS/C/应试/数值各与指针之间的区别.md
                  - 文件处理: CS/C/应试/文件处理.md
                  - 无类型指针: CS/C/应试/无类型指针.md
                  - 一个语句写在多行的方法: CS/C/应试/一个语句写在多行的方法.md
                  - 优先级: CS/C/应试/优先级.md
                  - 鼠标粗略法求最大公约数: CS/C/应试/鼠标粗略法求最大公约数.md
                  - 转义字符的长度: CS/C/应试/转义字符的长度.md
                  - 字符串处理: CS/C/应试/字符串处理.md
                  - 字符数组与字符指针: CS/C/应试/字符数组与字符指针.md
                  - 字面量: CS/C/应试/字面量.md
                  - 左值: CS/C/应试/左值.md

